pipeline {
   agent any
   stages {
      stage('build') {
         steps {
          dir('code/ch01_02'){
            sh(label: 'Build greeting', script: './scripts/build.sh')
          }
         }
      }
      stage('test') {
         steps {
          dir('code/ch01_02'){
            sh(label: 'Test greeting', script: './scripts/test.sh')
            junit '**/TEST_*.xml'
          }
         }
      }
   }
}
