version: "2.4"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        - TAG=${JENKINS_VERSION}
    environment:
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
      JENKINS_OPTS: >-
        --httpPort=8181 --sessionTimeout=1 --sessionEviction=60
    privileged: true
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - 8181:8181
      - 5005:5005
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8181"]
      retries: 10
      interval: 20s
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network-test:
        aliases:
          - jenkins


  saml:
    container_name: saml
    image: ghcr.io/kuisathaverat/docker-test-saml-idp:1.17.0
    environment:
      - SIMPLESAMLPHP_ADMIN_PASSWORD=admin
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://jenkins.example.com:8181/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://jenkins.example.com:8181/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://jenkins.example.com:8181/logout
      - SIMPLESAMLPHP_SESSION_DURATION=120
    privileged: true
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -Ls http://localhost:8080/simplesaml"]
      retries: 10
      interval: 20s
    networks:
      network-test:
        aliases:
          - saml

networks:
  network-test:
