version: "2.4"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        - TAG=${JENKINS_VERSION}
    environment:
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    mem_limit: 1000m
    cpus: 0.5
    privileged: true
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - 8080:8080
      - 5005:5005
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080"]
      retries: 10
      interval: 20s
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network-test:
        aliases:
          - jenkins


  saml:
    container_name: saml
    build:
      context: ./simplesamlphp
      dockerfile: Dockerfile
    environment:
      - SIMPLESAMLPHP_ADMIN_PASSWORD=admin
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://jenkins.example.com:8080/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://jenkins.example.com:8080/securityRealm/finishLogin
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://jenkins.example.com:8080/logout
    mem_limit: 1000m
    cpus: 0.5
    privileged: true
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - 80:80
    healthcheck:
      test: ["CMD-SHELL", "curl -Ls http://localhost/simplesaml"]
      retries: 10
      interval: 20s
    networks:
      network-test:
        aliases:
          - saml

networks:
  network-test:
