version: "2.4"
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      args:
        - TAG=${JENKINS_VERSION}
    environment:
      C_LANG: en_US.UTF-8
      JAVA_OPTS: >-
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.UsageStatistics.disabled=true
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
        -Dsun.jnu.encoding="UTF-8"
        -Dfile.encoding="UTF-8"
    mem_limit: 1000m
    cpus: 0.5
    privileged: true
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    ports:
      - 8080:8080
      - 5005:5005
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080"]
      retries: 10
      interval: 20s
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      network-test:
        aliases:
          - jenkins

  ssh-agent-rsa:
    container_name: ssh-agent-rsa
    build:
      context: ./ssh-agent-rsa
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      retries: 10
      interval: 10s
    depends_on:
      jenkins:
        condition: service_healthy
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    networks:
      network-test:
        aliases:
          - ssh-agent-rsa
networks:
  network-test:
